### ISSUE TITLE
Include recommendation to use a vertical-stack-card within the panel view

### ISSUE THREAD

**Issue by nielsrowinbik** [nielsrowinbik/lovelace-google-home-menu#3]
The example in `README.md` should be something along the lines of:
```yaml
views:
    - title: My Home
      icon: mdi:home-variant-outline
      path: home
      panel: true # recommended
      cards:
          - type: vertical-stack-card # recommended
             cards:
               - type: custom:google-home-menu
                  title: My Home
                  cards:
                      - type: custom:google-home-menu-item
                        color: yellow
                        entity: group.all_lights
                        label: Lights
                        icon: mdi:lightbulb-outline
```
Just setting `panel: true` won't work, as that only renders the first card.
